name: Run Robot Framework Tests

# Define quando o workflow deve rodar (sempre que houver push na main)
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Utilizando uma imagem Ubuntu para rodar os testes

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Setar o Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Define a versão do Python que você quer usar

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install -y \
            chromium-browser \
            chromium-chromedriver

      # Passo 4: Rodar os testes
      - name: Run Robot Framework tests
        run: |
          # Rodar os testes da pasta 'tests'
          robot tests/
