name: Run Robot Framework Tests

# Define quando o workflow deve rodar (sempre que houver push na main)
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Utilizando uma imagem Ubuntu para rodar os testes

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Setar o Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Define a versão do Python que você quer usar

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      # Passo 4: Rodar os testes
      - name: Run Robot Framework tests
        env:
          CHROME_BIN: /usr/bin/google-chrome-stable
          CHROMEDRIVER_PATH: /usr/lib/chromium-browser/chromedriver
        run: |
          robot --outputdir results/ tests/

      - name: Salvar relatórios como artefatos
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: results/
